services:
  agro-feira-database:
    image: postgres:18.3
    container_name: agro-feira-database
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
    restart: on-failure
    networks:
      - app-private-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  agro-feira-backend:
    container_name: agro-feira-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://agro-feira-database:5432/${POSTGRES_DB:-postgres}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      MAIL_USERNAME: ${MAIL_USERNAME:-lmts@ufape.edu.br}
      MAIL_PASSWORD: ${MAIL_PASSWORD:-abcdefghijklmnop}
    depends_on:
      agro-feira-database:
        condition: service_healthy
    networks:
      - app-private-network

volumes:
  postgres-data:

networks:
  app-private-network:
    driver: bridge
    name: app-private-network